
name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          pip install --upgrade pip wheel setuptools
          pip install -r requirements/default.txt -r requirements/test.txt
          pip list

      - name: Test with unittest
        run: |
          python -m unittest discover -s tests